### ISSUE TITLE
演示API已迁移到render部署，大量使用该API造成的权限禁用风险概不负责

### ISSUE THREAD

**Issue by lvguanjun** [lvguanjun/copilot_to_chatgpt4#10]
## 说明：

1. 演示API，即 `chatserver.3211000.xyz` 已经迁移到render部署，因为render是3个出口ip漂移，可能增加权限禁用风险
2. 后续会禁止将该接口接入 `oneapi` ，目前禁用特征即 `UA="Go-http-client/2.0"` & `Referer=""`，使用go客户端的被误伤可以添加一下Referer
3. 第2条规则简单的拦截无脑号商接入oneapi，会改代码跳过拦截的建议自行部署copilot_to_chat，不要往死里薅羊毛

## 其他：

简单的说下为什么做拦截，因为GitHub限制了单个客户端的最大连接数是10，本仓代码为了复用，是全局的一个httpx的客户端，因此同一时间向GitHub请求的最大链接数是10，~~当号商大量的请求压过来（即使我设置了3/10s的限速，也扛不住多个号商的请求），会导致我们的正常请求等待然后超时，这是这段时间公益站 `chat.3211000.xyz` 为什么经常超时的原因。~~

> 可能是代码bug，目前不太确定。

> 注：我的vps就1c1g，没考虑起多个服务负载均衡

## 罪证：

![log](https://github.com/lvguanjun/copilot_to_chatgpt4/assets/58430934/de4801b6-a243-45a1-a9bd-3fa784c07281)

**Comment by kindle939393** [comment]
请问怎么创建自己的api，已有VPS

**Comment by lvguanjun** [comment]
> 请问怎么创建自己的api，已有VPS,并且docker搭建cocopilot-gpt这个项目，不知道如何使用，加了v1没用

没太理解，搭建的服务是什么服务

**Comment by kindle939393** [comment]
> > 请问怎么创建自己的api，已有VPS,以及docker搭建cocopilot-gpt这个项目，不知道怎么用，加了v1没用
> 
> 不太理解，搭建的服务是什么服务

没事了我解决了，就是想问怎么搭建cocopilot的接口地址，以便于自己在next-web使用

**Comment by 1137882300** [comment]
> > > 请问怎么创建自己的api，已有VPS,以及docker搭建cocopilot-gpt这个项目，不知道怎么用，加了v1没用
> > 
> > 
> > 不太理解，搭建的服务是什么服务
> 
> 没事了我解决了，就是想问怎么搭建cocopilot的接口地址，以便于自己在next-web使用

怎么弄的可以说一下嘛？大佬

**Comment by lvguanjun** [comment]
按照readme部署就行了啊...
