### ISSUE TITLE
老哥，用的多的情况下，突然发现，流式不可用，非流式可用

### ISSUE THREAD

**Issue by leezhuuu** [lvguanjun/copilot_to_chatgpt4#17]
老哥，用的多的情况下，发现，流式不可用，非流式可用，这是怎么回事
![IMG_20240223_165128](https://github.com/lvguanjun/copilot_to_chatgpt4/assets/69389053/8dc0f602-b847-4af4-ba11-9f3766bff3f4)

**Comment by lvguanjun** [comment]
日志有什么报错吗？或者代码更新试一试
