### ISSUE TITLE
输入长文本时会请求失败

### ISSUE THREAD

**Issue by cxk-521** [lvguanjun/copilot_to_chatgpt4#18]

**Comment by lvguanjun** [comment]
有日志或者报错信息吗，或者示例请求也可以

**Comment by lvguanjun** [comment]
你说的是翻译的时候长文本吗？可能触发的是 github copilot 的审查（非编程问题），这个应该无解

部分规避的方案：
1. 用中文 prompy
2. 用代码块包起来
