### ISSUE TITLE
一些情况下和openai api接口不兼容

### ISSUE THREAD

**Issue by fanyiyang** [lvguanjun/copilot_to_chatgpt4#5]

**Comment by lvguanjun** [comment]
具体的呢？截图或者描述看看

**Comment by fanyiyang** [comment]
在使用metagpt的时候api不能用。本地curl实验过是没问题的，报authetication error，不知道和我看metagpt里是用' '有关系吗？

**Comment by lvguanjun** [comment]
不确定，可能是请求头的authetication丢失了
