### ISSUE TITLE
请问大佬，自己搭建的无法正常返回

### ISSUE THREAD

**Issue by goodstudy12** [lvguanjun/copilot_to_chatgpt4#6]
本地运行时，会返回：{"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}

直接用大佬的https://chatserver.3211000.xyz就是正常的

是不是因为无法访问https://api.githubcopilot.com/chat/completions接口呀

**Comment by leezhuuu** [comment]
我在自己电脑上部署不能正常运行，在新加坡服务器上部署就可以运行了

**Comment by leezhuuu** [comment]
可能是网络因素

**Comment by lvguanjun** [comment]
可能是网络因素也可能不是，但是这个报错
```
{"message":"Bad credentials","documentation_url":"[https://docs.github.com/rest"}](https://docs.github.com/rest%22%7D)
```
是获取copilot token时的报错，你可以单独请求试一下，我怀疑有可能token写错了

**Comment by goodstudy12** [comment]
> 可能是网络因素也可能不是，但是这个报错
> 
> ```
> {"message":"Bad credentials","documentation_url":"[https://docs.github.com/rest"}](https://docs.github.com/rest%22%7D)
> ```
> 
> 是获取copilot token时的报错，你可以单独请求试一下，我怀疑有可能token写错了

是不是因为我使用的ccu所以不能用。只能使用ghu吗？可是我用你的接口居然可以正常使用。

**Comment by lvguanjun** [comment]
对的，只能使用ghu，为了防止滥用，目前我的接口也不支持ccu了
