### ISSUE TITLE
希望作者能够给api支持修改温度值的功能

### ISSUE THREAD

**Issue by leezhuuu** [lvguanjun/copilot_to_chatgpt4#7]
希望作者能够给api支持修改温度值的功能

**Comment by lvguanjun** [comment]
当前代码支持的，在json data里面的temperature参数吧应该是，当前代码考虑伪装copolot插件行为，所以只接受了copilot插件请求的参数，其他的chatgpt的参数可能不支持

**Comment by lvguanjun** [comment]
如果你确信是chatgpt和copilot chat的参数名不一致但功能一致，可以截图补充一下，后续考虑做一个参数映射，这样可以直接通过客户端修改参数

**Comment by leezhuuu** [comment]
根据我个人的感觉判断，我觉得温度值修改后没有作用

**Comment by leezhuuu** [comment]
还是尽量模仿copilot的参数，这样减少被封的概率

**Comment by lvguanjun** [comment]
copilot chat官方行为确实判断不准，😂好像有佬试过温度改成0响应也会不一致，你可以试试，这都是copilot chat本身的行为，参数已经跟着请求过去了。

**Comment by leezhuuu** [comment]
OK

**Comment by leezhuuu** [comment]
真能熬
