### ISSUE TITLE
老哥，目前有没有封号案例呢？

### ISSUE THREAD

**Issue by leezhuuu** [lvguanjun/copilot_to_chatgpt4#8]
老哥，目前有没有封号案例呢？

**Comment by leezhuuu** [comment]
我目前没看见有封号的，你确定有封号的吗

**Comment by lvguanjun** [comment]
准确的说不是封号，是禁用copilot权限，不过因为copilot权限本身是非正常信用卡试用，所以不确定是否是copilot to chat+非正常信用卡试用导致的还是 copilot to chat 导致的

**Comment by leezhuuu** [comment]
昨天我淘宝买的一个"高校合作"的账号cop权限掉了，淘宝店家重新给我补了个手工学生认证的

**Comment by lvguanjun** [comment]
> 昨天我淘宝买的一个"高校合作"的账号cop权限掉了，淘宝店家重新给我补了个手工学生认证的

因为这些号的来源本身就不正常，所以目前也不太明确，到什么程度可能导致掉copilot权限

**Comment by neophack** [comment]
![image](https://github.com/lvguanjun/copilot_to_chatgpt4/assets/12814250/cf40a45a-2ef4-411c-bdf5-8bec70fe035c)
用了转chatgpt后。官方的插件和代理的chatgpt回答很短就断了

**Comment by lvguanjun** [comment]
> ![image](https://private-user-images.githubusercontent.com/12814250/293349911-cf40a45a-2ef4-411c-bdf5-8bec70fe035c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NDgyODQsIm5iZiI6MTcwMzg0Nzk4NCwicGF0aCI6Ii8xMjgxNDI1MC8yOTMzNDk5MTEtY2Y0MGE0NWEtMmVmNC00MTFjLWJkZjUtOGJlYzcwZmUwMzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDExMDYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiNWJjY2E0MDZjOWNlYTI1Y2FmNDk5NzNhNWVlYWZlNzVhOWI0Y2Y3ZGYyYmIzNDQ4OTMxNzRiNjRiOTE4MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._T0N8o9npd1WvF-cOo1JsD-qOAk2HaFx6PMTC9F7fPo) 用了转chatgpt后。官方的插件和代理的chatgpt回答很短就断了

应该不是项目原因哦，get filtered，我猜测可能是匹配到公共代码，然后你禁止了公共代码匹配吧，先排查下是不是这个原因

**Comment by lvguanjun** [comment]
建议这种问题新开一个issue，不然容易看不到

**Comment by neophack** [comment]
> > ![image](https://private-user-images.githubusercontent.com/12814250/293349911-cf40a45a-2ef4-411c-bdf5-8bec70fe035c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NDgyODQsIm5iZiI6MTcwMzg0Nzk4NCwicGF0aCI6Ii8xMjgxNDI1MC8yOTMzNDk5MTEtY2Y0MGE0NWEtMmVmNC00MTFjLWJkZjUtOGJlYzcwZmUwMzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDExMDYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiNWJjY2E0MDZjOWNlYTI1Y2FmNDk5NzNhNWVlYWZlNzVhOWI0Y2Y3ZGYyYmIzNDQ4OTMxNzRiNjRiOTE4MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._T0N8o9npd1WvF-cOo1JsD-qOAk2HaFx6PMTC9F7fPo) 用了转chatgpt后。官方的插件和代理的chatgpt回答很短就断了
> 
> 应该不是项目原因哦，get filtered，我猜测可能是匹配到公共代码，然后你禁止了公共代码匹配吧，先排查下是不是这个原因

好像是公共代码的问题csdn找的代码，我试了其他的没问题。
